# Generated by Django 5.0.6 on 2026-06-19 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(help_text="Driver's starting location (city / address).", max_length=255)),
                ('pickup_location', models.CharField(help_text='Pickup / loading location.', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Delivery / dropoff location.', max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Hours already used in the current 70-hr HOS cycle (0–70).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_json', models.JSONField(blank=True, help_text='Cached full API response from the HOS engine.', null=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
